"""conversations messages quotes comparisons redlines

Revision ID: 224bfb93426d
Revises: 985248dfa42f
Create Date: 2026-10-02 16:59:24.593722

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '224bfb93426d'
down_revision: Union[str, None] = '985248dfa42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_a_id', sa.String(length=36), nullable=False),
    sa.Column('document_b_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_source', sa.String(length=16), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_a_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_b_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_document_a_id'), 'comparisons', ['document_a_id'], unique=False)
    op.create_index(op.f('ix_comparisons_document_b_id'), 'comparisons', ['document_b_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('stopped', sa.Boolean(), nullable=False),
    sa.Column('coverage_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('redlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('applied_json', sa.JSON(), nullable=True),
    sa.Column('dropped_json', sa.JSON(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redlines_document_id'), 'redlines', ['document_id'], unique=False)
    op.create_table('comparison_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('significance', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_source', sa.String(length=16), nullable=False),
    sa.Column('a_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('b_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('a_start', sa.Integer(), nullable=True),
    sa.Column('a_end', sa.Integer(), nullable=True),
    sa.Column('b_start', sa.Integer(), nullable=True),
    sa.Column('b_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_changes_comparison_id'), 'comparison_changes', ['comparison_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=512), nullable=False),
    sa.Column('ref', sa.String(length=8), nullable=True),
    sa.Column('ref_index', sa.Integer(), nullable=False),
    sa.Column('text', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('match_kind', sa.String(length=16), nullable=True),
    sa.Column('fail_reason', sa.String(length=32), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_document_id'), 'quotes', ['document_id'], unique=False)
    op.create_index(op.f('ix_quotes_message_id'), 'quotes', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_message_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_document_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_comparison_changes_comparison_id'), table_name='comparison_changes')
    op.drop_table('comparison_changes')
    op.drop_index(op.f('ix_redlines_document_id'), table_name='redlines')
    op.drop_table('redlines')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_comparisons_document_b_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_document_a_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_table('conversations')
    # ### end Alembic commands ###
